title: Your Title

plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-remote-theme

remote_theme: pages-themes/primer

# include:
  # - README.md
  # - LICENSE
  # - LICENCE
  # - COPYING
  # - CODE_OF_CONDUCT
  # - CONTRIBUTING
  # - ISSUE_TEMPLATE
  # - PULL_REQUEST_TEMPLATE
